"""Add payment_status to orders

Revision ID: 11f5f3a8fb84
Revises: 8a6c199924c7
Create Date: 2025-05-24 22:26:57.030505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f5f3a8fb84'
down_revision = '8a6c199924c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
