"""Enable cascade delete on order_items

Revision ID: 12480fc3fd19
Revises: 11f5f3a8fb84
Create Date: 2025-05-27 01:16:52.330286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12480fc3fd19'
down_revision = '11f5f3a8fb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('order_items_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_order_id_fkey', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
