"""Add product_name snapshot to order_items

Revision ID: 4e4d1100c78d
Revises: 12480fc3fd19
Create Date: 2025-05-27 01:22:41.024393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4d1100c78d'
down_revision = '12480fc3fd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
