"""Add price to OrderItem

Revision ID: 8a6c199924c7
Revises: 9e6cf1a4b9ed
Create Date: 2025-05-24 19:23:00.582929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6c199924c7'
down_revision = '9e6cf1a4b9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
