"""Added reset_token and reset_token_expiration to User model

Revision ID: d63e3653cb44
Revises: 
Create Date: 2025-05-23 01:06:55.905788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd63e3653cb44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('payment_method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.drop_constraint('orders_order_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('orders_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('order_date')
        batch_op.drop_column('order_id')
        batch_op.drop_column('shipping_status')
        batch_op.drop_column('phone')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('name')
        batch_op.drop_column('total')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipping_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['order_id'])
        batch_op.drop_constraint('user_settings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('language')
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.LargeBinary(),
               existing_nullable=True,
               postgresql_using='avatar::bytea')  # Explicitly cast using `USING`
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('avatar',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               postgresql_using='avatar::varchar')  # Revert the `avatar` column
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_settings_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('delivery_status')
        batch_op.drop_column('shipping_status')
        batch_op.drop_column('order_date')
        batch_op.drop_column('total')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('delivery_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shipping_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('orders_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('orders_order_id_key', ['order_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_region')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_name')
        batch_op.drop_column('avatar')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
